name: Trigger Netlify Build

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Curl POST to Netlify Build Hook
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/6817509303b058575409855c
