name: Trigger Scheduled Netlify Build

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Curl POST to Netlify Build Hook
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK_URL }}